class: metaworld
name: "metaworld-${env.task}"
embodiment: sawyer
task: door-open
supported_tasks:
  - assembly
  - basketball
  - bin-picking
  - box-close
  - button-press-topdown
  - button-press-topdown-wall
  - button-press
  - button-press-wall
  - coffee-button
  - coffee-pull
  - coffee-push
  - dial-turn
  - disassemble
  - door-close
  - door-lock
  - door-open
  - door-unlock
  - hand-insert
  - drawer-close
  - drawer-open
  - faucet-open
  - faucet-close
  - hammer
  - handle-press-side
  - handle-press
  - handle-pull-side
  - handle-pull
  - lever-pull
  - peg-insert-side
  - pick-place-wall
  - pick-out-of-hole
  - reach
  - push-back
  - push
  - pick-place
  - plate-slide
  - plate-slide-side
  - plate-slide-back
  - plate-slide-back-side
  - peg-unplug-side
  - soccer
  - stick-push
  - stick-pull
  - push-wall
  - reach-wall
  - shelf-place
  - sweep-into
  - sweep
  - window-open
  - window-close
action_repeat: 2
render: false
size: [64, 64]
sensors:
  state:
    modility: tabular
    order: second
  image:
    modility: visual
    order: first