defaults:
  - _self_
  - runtime: local
  - data: default
  - env: ???
  - version: default

demonstration_dataset_name: ??

algo_name: bc
seed: 42
log_name: "${env.name}/${environment_setup}/${demonstration_dataset_name}/${algo_name}/${seed}/${now:%Y-%m-%d-%H-%M-%S}"
stack: 3
batch_size: 50
train_validation_split_ratio: 0.7
num_expert_trajectories: 100
num_test_trajectories: 100
patience: 3
min_policy_epoch: 50

policy_lr: 1e-3
grad_clip: 100.0

environment_setup: visual

encoders:
  tabular:
    name: identity
  visual:
    name: cnn_ha

policy:
  hidden_size: 128
  hidden_layers: 2